on:
  push:
    branches:
      - kerpz

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: archlinux:latest

    steps:
      - name: Install packages
        run: |
          pacman -Syyu --noconfirm base-devel arm-none-eabi-gcc arm-none-eabi-newlib git python-pip python-crcmod
          
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: safe.directory
        run: git config --global --add safe.directory /__w/uv-k5-firmware-custom/uv-k5-firmware-custom        

      - name: Build firmware
        run: |
          make
          arm-none-eabi-size firmware

      - name: Copy output
        run: cp firmware*.bin /__w/uv-k5-firmware-custom/firmware.bin

      - name: Save build artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: /__w/uv-k5-firmware-custom/firmware.bin

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download firmware artifact
        uses: actions/download-artifact@v3
        with:
          name: firmware
          path: .

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: firmware.bin
          asset_name: egzumer_${{ github.ref_name }}.bin
          tag: ${{ github.ref }}
          overwrite: true
          release_name: release ${{ github.ref_name }}
